#定义配置信息
MonkeyConfig:
    #定义异常字段
    Exceptions:
        [
        'NullPointer','IllegalState','IllegalArgument','ArrayIndexOutOfBounds','RuntimeException','SecurityException','ANR','CRASH',
        'EXCEPTION','FATAL','ClassNotFoundException','StackOverflowError','OutOfMemoryError'
        ]
    #定义测试设备
    device_Name:
        '2264d8ba'
    #用本地设备中第几个设备进行测试，通常是第1个
    device_ord: 1
    #定义测试包名
    packapgname:
        'co.runner.app'
    #定义启动的activtiy
    appActivity:
        'co.runner.app/.home_v4.activity.HomeActivityV4'
    #事件间隔时间,单位毫秒
    throttle: 300
    #定义执行随机事件总数
    count: 100000

    ##引导功能，再执行Monkey前，引导进入指定模块下，基于bounds相对坐标方式实现，此种方式引导在selectElements引导为空时采用此项数据引导；
    ##获取坐标方法：可通过uiautomatorviewer.bat工具抓取坐标，如元素bounds值为[864,1626][1080,1776]，则x,y坐标为(864,1776)
    #进入【我的】 (851,1872)
    #进入【广场】 (108,1872)
    #进入【跑步】 (300,1836)
    #进入【阿凡达】 (255,1306)
    selectList: []
    #selectList: [(108,1872)]

    ##当使用resourceId时手工取，如co.runner.app:id/iv_tab_me
    ##引导功能，再执行Monkey前，引导进入指定模块下,基于uiautomator框架控件识别实现
    #进入【我的】 co.runner.app:id/iv_tab_me
    #进入【广场】 co.runner.app:id/iv_tab_discover
    #进入【跑步】 co.runner.app:id/btn_run
    #进入【阿凡达】 co.runner.app:id/iv_avatar_trousers
    #优先使用selectElements，如为空或异常才使用selectList数据
    selectElements:
        #- 'text=跳过'   #处理广告跳过
        #- '确定'        #处理首页弹窗
        - 'text=广场'
        - 'text=跑步路线'

    #URL黑名单限制
    blackUrlList:
    - "co.runner.app/co.runner.avatar.ui.activity.AvatarEditActivity"           #首页-阿凡达页面
    - "co.runner.app/.ui.record.RecordHistoryActivity"                          #首页-阿凡达-历史跑步记录列表
    - "co.runner.app/.activity.record.RecordDataActivity"                       #首页-阿凡达-历史跑步记录-跑步记录
    - "co.runner.app/co.runner.user.activity.MyLevelActivity"                   #首页-阿凡达-历史跑步记录列表-我的等级页面
    - "co.runner.app/.ui.record.RunActivityV2"                                  #首页-跑步主页面
    - "co.runner.app/co.runner.badge.activity.BadgeActivityV2"                  #首页-我的勋章列表页面 
    - "co.runner.app/.view.equipment.MyEquipmentActivity"                       #首页-我的装备列表页面  
    - "co.runner.app/co.runner.middleware.activity.NearbyActivity"              #首页-身边列表页面   
    - "co.runner.app/co.runner.middleware.activity.RecommandEventsActivity"     #首页-推荐活动页面     
    #- "co.runner.app/.ui.feed.feedlist.TopicMainActivity"                       #广场-话题列表页面
    #- "co.runner.app/.view.event.ui.OfflineEventActivity"                       #广场-赛事列表页面
    #- "co.runner.app/co.runner.marathon.activity.OlMarathonListActivityV2"      #广场-线上马页面
    #- "co.runner.app/.view.event.ui.RunningEventActivity"                       #广场-活动页面
    - "co.runner.app/co.runner.talk.activity.TalkMainActivity"                  #广场-专栏页面
    #- "co.runner.app/co.runner.bet.activity.BetClassListL2Activity"             #广场-约定跑页面
    - "co.runner.app/co.runner.crew.activity.DiscoverCrewActivity"              #广场-跑团列表页面
    - "co.runner.app/.ui.brand.DiscoverBrandsActivity"                          #广场-品牌列表页面
    - "co.runner.app/co.runner.training.activity.TrainPlanDetailActivity"       #广场-训练计划页面
    - "co.runner.app/co.runner.training.activity.TrainPlanDetailActivity"       #广场-训练计划页面
    #- "co.runner.app/co.runner.rundomain.ui.list.RunDomainListActivity"         #广场-跑步线路列表页面
    - "co.runner.app/.ui.tool.QRCodeActivity"                                   #广场-扫一扫页面
    - "co.runner.app/co.runner.other.activity.SearchTopicAndArticleActivity"    #广场-搜索页面
    - "co.runner.app/.activity.feed.FeedMineActivity"                           #我的-跑友动态
    - "co.runner.app/co.runner.crew.ui.main.MyCrewActivity"                     #我的-我的跑团
    - "co.runner.app/co.runner.wallet.activity.WalletActivity"                  #我的-我的钱包
    - "co.runner.app/.rong.activity.ConversationListActivity"                   #我的-消息
    - "co.runner.app/co.runner.user.activity.FriendsActivity"                   #我的-跑友
    - "co.runner.app/.activity.account.ProfileEditActivity"                     #我的-资料编辑页面
    - "co.runner.app/co.runner.shoe.activity.UserShoeListChoiceListActivity"    #Shoe选择页面
    - "co.runner.app/.activity.record.RecordMonthChartActivity"                 #月跑量图
    - "co.runner.app/.activity.tools.WebViewActivity"                           #webview页面
    - "co.runner.app/.activity.account.LoginActivity"                           #登录注册页面
    - "co.runner.app/.ui.more.setting.SettingActivity"                          #偏好设置页面
    - 'co.runner.app/co.runner.badge.activity.UpgradeActivity'
    #- 'co.runner.app/.ui.feed.feedlist.TopicMainActivity'
    #- 'co.runner.app/co.runner.avatar.ui.activity.AvatarMainActivity'
    #- 'co.runner.app/.component.router.ShortChainTransferActivity'
    #- 'co.runner.app/.view.event.ui.OfflineEventActivity'
    #- 'co.runner.app/.ui.brand.FeedBrandListActivity'
    #- 'co.runner.app/.activity.tools.ImageActivity'
    #- 'co.runner.app/.activity.tools.media.ImagesActivityV2'
    #- 'co.runner.app/.ui.brand.DiscoverBrandsActivity'
    #- 'co.runner.app/co.runner.user.activity.UserActivity'
    #- 'co.runner.app/.ui.record.BestRecordActivity'
    #- 'co.runner.app/.ui.crew.crew.CrewActivity'
    #- 'co.runner.app/co.runner.crew.activity.CrewAppEventDetailActivity'
    #- 'co.runner.app/co.runner.crew.ui.guide.GuideActivity'
    #- 'co.runner.app/co.runner.user.activity.UserInfoSettingActivity'
    #- 'co.runner.app/co.runner.user.activity.RemarkActivity'
    #- 'co.runner.app/co.runner.crew.ui.detaiInfo.CrewDetailActivity'
    

    #元素、文本黑名单限制
    blackList:
       ['WLAN','移动数据','飞行模式','删除','发布动态','Delete','delete','del','相机','拍照','相机胶卷','编辑图片','说点什么','发布动态','发布','退出登录']

    #控制开关，是否启用uiautomator黑名单，引导功能，当为on则为启动，设置为off，则黑名单无效，调用坐标引导。
    switchUiautomator: 'on'

    #点击事件的百分比
    pct-touch: 80
    #滑动事件的百分比
    pct-motion : 5
    #方向导航事件的百分比
    pct-nav: 10
    #主要导航事件的百分比
    pct-majornav: 5

    ## 【V:明细,D:调试，I:Info信息，W：警告信息，Error：错误信息,F:严重错误,S:不记载】
    logLevel: 'D'

