# Generated by Django 2.1.4 on 2018-12-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_auto_20181226_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleinfo',
            old_name='folder_path',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='projectinfo',
            old_name='root_path',
            new_name='file_path',
        ),
    ]
