# Generated by Django 2.1.4 on 2018-12-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_auto_20181230_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=120, verbose_name='密码'),
        ),
    ]
