# Generated by Django 2.1.4 on 2019-01-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0004_auto_20181231_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinfo',
            name='file_path',
            field=models.CharField(max_length=200, verbose_name='模块路径'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='file_path',
            field=models.CharField(max_length=200, verbose_name='项目路径'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='file_path',
            field=models.CharField(max_length=200, verbose_name='用例文件路径'),
        ),
    ]
